@base_url=http://localhost:3000

### Get events
GET {{base_url}}/events

### Get one event
GET {{base_url}}/events/{{eventId}}

### Create event
# @name createEvent
POST {{base_url}}/events
Content-Type: application/json

{
    "name": "My new event",
    "description": "Description of the new event",
    "date": "2019-03-03T00:00:00",
    "price": 100
}

###
@eventId = {{createEvent.response.body.id}}

### Update event
PATCH {{base_url}}/events/{{eventId}}
Content-Type: application/json

{
    "name": "My edited new event",
    "description": "Description of the new event",
    "date": "2020-01-01T00:00:00",
    "price": 100
    
}

### Delete event
DELETE {{base_url}}/events/{{eventId}}


### Get one event's spots
GET {{base_url}}/events/{{eventId}}/spots

### Get one event's specific spot (checar)
GET {{base_url}}/events/{{eventId}}/spots/{{eventId}} 

### Create spot for event
# @name createSpot
POST {{base_url}}/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "A1"
}

###

@spotName = {{createSpot.response.body.name}}

### Reserve 
POST {{base_url}}/events/{{eventId}}/reserve
Content-Type: application/json

{
    "spots": ["{{spotName}}"],
    "ticket_kind": "full",
    "email": "test@test.com"
}